# -*- coding: utf-8 -*-
# This file was *autogenerated* from the file QuickPower.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
def QuickPower(a, n, p):
	tmp = a
	ret = _sage_const_1 
	while (n > _sage_const_0 ) :
		if (n & _sage_const_1 ):
			ret = (ret * tmp) % p;
		tmp = (tmp * tmp) % p;
		n >>= _sage_const_1 ;
	return ret

if __name__ == '__main__':
	print("/*** calc a^n (mod p) ***/")
	try:
		a = int(input('a = '))
		n = int(input('n = '))
		p = int(input('p = '))
		print(QuickPower(a, n, p))
	except:
		print('Error Input !\n')
	
