# -*- coding: utf-8 -*-
# This file was *autogenerated* from the file Fermat.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
import random

def QuickPower(a, n, p): # calc a^n mod p
	tmp = a
	ret = _sage_const_1 
	while (n > _sage_const_0 ) :
		if (n & _sage_const_1 ):
			ret = (ret * tmp) % p;
		tmp = (tmp * tmp) % p;
		n >>= _sage_const_1 ;
	return ret

def Fermat(x, T): # Fermat Test
	if x < _sage_const_2  :
		return False
	if x <= _sage_const_3  :
		return True
	if x % _sage_const_2  == _sage_const_0  or x % _sage_const_3  == _sage_const_0  :
		return False
	for i in range(T):
		tmp = random.randint(_sage_const_2 , x-_sage_const_2 ) # pick a random number in [2, x-2]
		if QuickPower(tmp, x-_sage_const_1 , x) != _sage_const_1  :
			return False
	return True

if __name__ == '__main__' :
	print('/*** Fermat Prime Test ***/')
	try:
		x = int(input('Test for x : '))
		T = int(input('Test times : '))
	except:
		print('Error Input !')
	if Fermat(x, T):
		print('This is a prime')
	else:
		print("This isn't a prime")
